import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@nextui-org/react/button'
import dbConnect from '../lib/dbConnect'
import Activity from '../models/Activities.model'

export default function Home({ activities }) {
	console.log(activities)

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Activities</h1>
				{activities.map(({ _id, title, description, guests, imgUrl }) => (
					<div key={_id}>
            <img src={imgUrl} alt="" />
						<h3>{title}</h3>
            <h4>{guests}</h4>
						<p>{description}</p>
					</div>
				))}
			</main>
			{/* <Button>Hola</Button> */}
		</div>
	)
}

export async function getServerSideProps() {
	try {
		await dbConnect()

		const res = await Activity.find({})
		const activities = res.map(el => {
			const activity = el.toObject()
			activity._id = `${activity._id}`
			return activity
		})
		return { props: { activities } }
	} catch (error) {
		console.log(error)
	}
}
