import React from 'react'
import Head from 'next/head'
import { Card, Text } from '@nextui-org/react'
import Image from 'next/image'
import logoHome from '../public/logo_graf.svg'
import Link from 'next/link'

export default function index() {
	const list = [
		{ title: 'Actividades' },
		{ title: 'Talleres' },
		{ title: 'Mapa' },
		{ title: 'Firmas' },
		{ title: 'FAQ' },
	]
	return (
		<div className='max-w-md'>
			<Head>
				<title>Graf</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex flex-col justify-center py-6'>

				<Image src={logoHome} alt='Logo Graf' width={60} height={60} />
			</div>
			<div className='px-3' >
				{list.map((item, index) => (
					
					<Link href={`/${item.title.toLowerCase()}`} passHref key={index}>
						<Card color='primary' bordered='false' clickable key={item.title} className='py-6 my-2 bg-white'>
							<Text className='text-center' css={{ fontWeight: '$bold', color: '$black' }} transform='capitalize'>
								{item.title}
							</Text>
						</Card>
					</Link>
				))}
			</div>
		</div>
	)
}
